In [1]:
import os
import pandas as pd

PATH = "../"
files = os.listdir(os.path.join(PATH, 'data'))
files

['agency.txt',
 'calendar.txt',
 'frequencies.txt',
 'routes.txt',
 'shapes.txt',
 'stops.txt',
 'stop_times.txt',
 'Top10PopCities.csv',
 'trips.txt']

In [23]:
df_frequencies = pd.read_csv(os.path.join(PATH, 'data', files[2]))
df_routes = pd.read_csv(os.path.join(PATH, 'data', files[3]))
df_stops = pd.read_csv(os.path.join(PATH, 'data', files[5]))
df_stop_times = pd.read_csv(os.path.join(PATH, 'data', files[6]))
df_trips = pd.read_csv(os.path.join(PATH, 'data', files[8]))

In [7]:
df_frequencies

           trip_id start_time  end_time  headway_secs  exact_times
0     054300B000_1   06:00:00  22:00:00           720            0
1     054300B000_0   06:00:00  22:00:00           720            0
2     0100Z3H000_1   05:00:00  24:00:00           480            0
3     0100Z3H000_0   05:00:00  24:00:00           480            0
4     0100Z3G000_1   05:00:00  24:00:00           480            0
...            ...        ...       ...           ...          ...
1531  05A34BE000_0    5:00:00  24:00:00           480            0
1532  05334BE000_1    6:00:00  23:00:00           600            0
1533  05334BE000_0    6:00:00  23:00:00           600            0
1534  03100L6002_0    4:30:00  23:18:00           300            0
1535  03100L6002_1    4:47:00  23:02:00           300            0

[1536 rows x 5 columns]

In [11]:
df_routes[df_routes['agency_id'] == 'METRO']

,route_id,agency_id,route_short_name,route_long_name,route_type,route_color,route_text_color
52,CMX0200LB,METRO,B,Ciudad Azteca - Buenavista,1,118751,FFFFFF
53,CMX0200LA,METRO,A,Pantitlán - La Paz,1,A02D96,FFFFFF
54,CMX0200L9,METRO,9,Pantitlán - Tacubaya,1,512826,FFFFFF
55,CMX0200L8,METRO,8,Garibaldi - Constitución de 1917,1,118749,FFFFFF
56,CMX0200L7,METRO,7,El Rosario - Barranca del Muerto,1,E87511,FFFFFF
57,CMX0200L6,METRO,6,El Rosario - Martín Carrera,1,D81E05,FFFFFF
58,CMX0200L5,METRO,5,Politécnico - Pantitlán,1,F9D616,FFFFFF
59,CMX0200L4,METRO,4,Santa Anita - Martín Carrera,1,7FBCAA,FFFFFF
60,CMX0200L3,METRO,3,Indios verdes - Universidad,1,AD9B0C,FFFFFF
61,CMX0200L2,METRO,2,Cuatro Caminos - Tasqueña,1,0071C1,FFFFFF
159,CMX0200L1,METRO,1,Pantitlán - Observatorio,1,F94F8E,FFFFFF
269,CMX020L12,METRO,L12,Tláhuac-Mixcoac,1,B99E51,FFFFFF

In [12]:
df_stops

,stop_id,stop_name,stop_lat,stop_lon,zone_id,wheelchair_boarding
0,0501070-JBARRERA,Juan de la Barrera,19.509920,-99.188570,0501070-JBARRERA,0
1,0300L4-20NOVIEMBR,20 de Noviembre,19.429320,-99.134020,0300L4-MSCIUDAD,1
2,0300L4-PINOSRZSR,Pino Suárez Sur,19.426100,-99.134210,0300L4-20NOVIEMBR,1
3,0300L4-SANPABLO,San Pablo,19.425580,-99.130700,0300L4-SANPABLO,1
4,0300L4-FRAYSERVND,Fray Servando,19.423640,-99.130970,0300L4-FRAYSERVND,1
...,...,...,...,...,...,...
10216,05300B0-ENRMORAL,Enrique del Moral (frente edificio movistar),19.358624,-99.272258,05300B0-ENRMORAL,0
10217,05300B0-BAJPUENTE,Bajo puente de autopista México - la marquesa,19.357994,-99.276860,05300B0-BAJPUENTE,0
10218,05300B0-FDEZGRAEZ,Av. Carlos Fernandez Graez,19.353146,-99.281921,05300B0-FDEZGRAEZ,0
10219,05300B0-ACOXPTORRES,Calz. Acoxpa - Av. de las Torres,19.298580,-99.138650,05300B0-ACOXPTORRES,0
10220,05300B1-EZAPLCABRERA,Emiliano Zapata - Luis Cabrera,19.321810,-99.221750,05300B1-EZAPLCABRERA,0

In [20]:
df_stop_times['trip_id'].nunique() # 1155
df_stop_times

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,timepoint
0,010001A000_0,00:00:00,00:00:00,0100C100-PERIFHOLI,1,0
1,010001A000_0,00:03:37,00:03:37,010C1801-MAVILACONS,2,0
2,010001A000_0,00:05:02,00:05:02,010C1301-PERIFELEGAR,3,0
3,010001A000_0,00:06:35,00:06:35,010C1801-MAVILACEJNAL,4,0
4,010001A000_0,00:08:10,00:08:10,0100C100-PERIFHORACIO,5,0
...,...,...,...,...,...,...
40799,0950R10000_0,01:38:00,01:38:00,0900R3-DGSA,25,0
40800,0950R10000_0,01:42:05,01:42:05,0900R3-TIENDAUNAM2,26,0
40801,0950R10000_0,01:46:10,01:46:10,0900R3-FCPOLITICAS,27,0
40802,0950R10000_0,01:50:15,01:50:15,0900R3-IJURIDICAS2,28,0
40803,0950R10000_0,01:54:20,01:54:20,0900R6-MBCU,29,0

In [24]:
df_trips

,route_id,service_id,trip_id,trip_headsign,trip_short_name,direction_id,shape_id
0,CMX01001C,0,010001C000_1,Canal de Chalco - Barranca del Muerto,C.Base Periférico Canal de Chalco to Base Barr...,1,SH01001C000_1
1,CMX01001C,0,010001C000_0,Barranca del Muerto - Canal de Chalco,C.Base Barranca del Muerto to Base Periférico ...,0,SH01001C000_0
2,CMX01001B,0,010001B000_1,Canal de Chalco - Tacubaya,B.Base Periférico Canal de Chalco to Base Tacu...,1,SH01001B000_1
3,CMX01001B,0,010001B000_0,Tacubaya - Canal de Chalco,B.Base Tacubaya to Base Periférico Canal de Ch...,0,SH01001B000_0
4,CMX01001A,0,010001A000_1,Canal de Chalco - Cuatro Caminos,A.Base Canal de Chalco to Base Cuatro Caminos,1,SH01001A000_1
...,...,...,...,...,...,...,...
1150,CMX010Z3G,0,0100Z3G000_0,Base Av. 4 UACM Tezonco,Metro Taxqueña to UACM Tezonco x Escuela,0,SH010Z3G000_0
1151,CMX010Z3H,0,0100Z3H000_1,CETRAM STC Metro Tasqueña,UACM Tezonco to Metro Taxqueña x Torres,1,SH010Z3H000_1
1152,CMX010Z3H,0,0100Z3H000_0,Base Av. 4 UACM Tezonco,Metro Taxqueña to UACM Tezonco x Torres,0,SH010Z3H000_0
1153,CMX05300B,4,054300B000_1,Frente Centro comercial paseos Acoxpa,Santa Fe to Paseo Acoxpa,1,SH05300B000_1
1154,CMX05300B,4,054300B000_0,Av. Carlos Fernandez Graez,Paseo Acoxpa to Santa Fe,0,SH05300B000_0